// Code generated by "stringer --type Compass --trimprefix compass --linecomment"; DO NOT EDIT.

package city

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Origin-1]
	_ = x[Destination-2]
}

const _Compass_name = "OriginDestination"

var _Compass_index = [...]uint8{0, 6, 17}

func (i Compass) String() string {
	i -= 1
	if i < 0 || i >= Compass(len(_Compass_index)-1) {
		return "Compass(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Compass_name[_Compass_index[i]:_Compass_index[i+1]]
}
